# Generated by Django 4.1.13 on 2023-11-13 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_validator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='name_field',
        ),
    ]
